# Generated by Django 6.0.4 on 2026-05-07 15:54

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('location_room', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='scheduled', max_length=20)),
            ],
            options={
                'verbose_name': 'Evaluation Session',
                'verbose_name_plural': 'Evaluation Sessions',
                'ordering': ['scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_group_project', models.BooleanField(default=False)),
                ('submission_deadline', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('academic_year', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('examiner', 'Examiner'), ('student', 'Student')], max_length=20)),
                ('profile_picture_url', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CVAnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('gaze_direction', models.CharField(blank=True, max_length=100, null=True)),
                ('head_pose', models.CharField(blank=True, max_length=100, null=True)),
                ('hand_gesture', models.CharField(blank=True, max_length=100, null=True)),
                ('facial_expression', models.CharField(blank=True, max_length=100, null=True)),
                ('engagement_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cheating_flag', models.BooleanField(default=False)),
                ('cheating_reason', models.TextField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_analysis_results', to='core.evaluationsession')),
            ],
            options={
                'verbose_name': 'CV Analysis Result',
                'verbose_name_plural': 'CV Analysis Results',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ExaminerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='examiner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Examiner Profile',
                'verbose_name_plural': 'Examiner Profiles',
            },
        ),
        migrations.CreateModel(
            name='ExaminerActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('score_modified', 'Score Modified'), ('question_validated', 'Question Validated'), ('grade_approved', 'Grade Approved'), ('bulk_approved', 'Bulk Approved')], max_length=30)),
                ('action_detail', models.JSONField(blank=True, null=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examiner_action_logs', to='core.evaluationsession')),
                ('examiner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='core.examinerprofile')),
            ],
            options={
                'verbose_name': 'Examiner Action Log',
                'verbose_name_plural': 'Examiner Action Logs',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='HeartrateRawData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('bpm', models.IntegerField()),
                ('hrv_value', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('is_baseline', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartrate_data', to='core.evaluationsession')),
            ],
            options={
                'verbose_name': 'Heart Rate Raw Data',
                'verbose_name_plural': 'Heart Rate Raw Data',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='evaluationsession',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_sessions', to='core.project'),
        ),
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_file_url', models.TextField(blank=True, null=True)),
                ('github_repo_url', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.project')),
            ],
            options={
                'verbose_name': 'Project Submission',
                'verbose_name_plural': 'Project Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='evaluationsession',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_sessions', to='core.projectsubmission'),
        ),
        migrations.CreateModel(
            name='RubricCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
                ('weight_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_categories', to='core.project')),
            ],
            options={
                'verbose_name': 'Rubric Category',
                'verbose_name_plural': 'Rubric Categories',
            },
        ),
        migrations.CreateModel(
            name='RubricCriteria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criteria_name', models.CharField(max_length=255)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('weight_in_category', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='core.rubriccategory')),
            ],
            options={
                'verbose_name': 'Rubric Criteria',
                'verbose_name_plural': 'Rubric Criteria',
            },
        ),
        migrations.CreateModel(
            name='FinalScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ai_recommended_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('examiner_final_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('examiner_note', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('examiner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_scores', to='core.examinerprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_scores', to='core.evaluationsession')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_scores', to='core.rubriccriteria')),
            ],
            options={
                'verbose_name': 'Final Score',
                'verbose_name_plural': 'Final Scores',
            },
        ),
        migrations.CreateModel(
            name='AIScoreRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ai_recommended_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('xai_explanation', models.TextField(blank=True, null=True)),
                ('shap_values', models.JSONField(blank=True, null=True)),
                ('confidence_level', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_score_recommendations', to='core.evaluationsession')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_score_recommendations', to='core.rubriccriteria')),
            ],
            options={
                'verbose_name': 'AI Score Recommendation',
                'verbose_name_plural': 'AI Score Recommendations',
            },
        ),
        migrations.CreateModel(
            name='SessionRecording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_file_url', models.TextField(blank=True, null=True)),
                ('audio_file_url', models.TextField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='core.evaluationsession')),
            ],
            options={
                'verbose_name': 'Session Recording',
                'verbose_name_plural': 'Session Recordings',
            },
        ),
        migrations.CreateModel(
            name='SessionSummaryReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_ai_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total_final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('overall_feedback', models.TextField(blank=True, null=True)),
                ('emotional_summary', models.TextField(blank=True, null=True)),
                ('integrity_flags_summary', models.TextField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_reports', to='core.examinerprofile')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary_report', to='core.evaluationsession')),
            ],
            options={
                'verbose_name': 'Session Summary Report',
                'verbose_name_plural': 'Session Summary Reports',
            },
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_groups', to='core.project')),
            ],
            options={
                'verbose_name': 'Student Group',
                'verbose_name_plural': 'Student Groups',
            },
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='core.studentgroup'),
        ),
        migrations.AddField(
            model_name='evaluationsession',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_sessions', to='core.studentgroup'),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('degree_program', models.CharField(blank=True, max_length=255, null=True)),
                ('academic_year', models.IntegerField(blank=True, null=True)),
                ('batch', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
            },
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='core.studentprofile'),
        ),
        migrations.AddField(
            model_name='evaluationsession',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_sessions', to='core.studentprofile'),
        ),
        migrations.CreateModel(
            name='VivaQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('blooms_level', models.CharField(blank=True, choices=[('Remember', 'Remember'), ('Understand', 'Understand'), ('Apply', 'Apply'), ('Analyze', 'Analyze'), ('Evaluate', 'Evaluate'), ('Create', 'Create')], max_length=20, null=True)),
                ('question_order', models.IntegerField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viva_questions', to='core.evaluationsession')),
            ],
            options={
                'verbose_name': 'Viva Question',
                'verbose_name_plural': 'Viva Questions',
                'ordering': ['question_order'],
            },
        ),
        migrations.CreateModel(
            name='VivaAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transcribed_answer', models.TextField(blank=True, null=True)),
                ('audio_clip_url', models.TextField(blank=True, null=True)),
                ('response_delay_ms', models.IntegerField(blank=True, null=True)),
                ('pause_frequency', models.IntegerField(blank=True, null=True)),
                ('speech_clarity_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ai_answer_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viva_answers', to='core.studentprofile')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.vivaquestion')),
            ],
            options={
                'verbose_name': 'Viva Answer',
                'verbose_name_plural': 'Viva Answers',
            },
        ),
        migrations.CreateModel(
            name='ProjectExaminer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_project', models.CharField(choices=[('lead', 'Lead'), ('co-examiner', 'Co-Examiner')], max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('examiner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='core.examinerprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_examiners', to='core.project')),
            ],
            options={
                'verbose_name': 'Project Examiner',
                'verbose_name_plural': 'Project Examiners',
                'constraints': [models.UniqueConstraint(fields=('project', 'examiner'), name='unique_project_examiner')],
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.studentgroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='core.studentprofile')),
            ],
            options={
                'verbose_name': 'Group Member',
                'verbose_name_plural': 'Group Members',
                'constraints': [models.UniqueConstraint(fields=('group', 'student'), name='unique_group_student')],
            },
        ),
    ]
