# Generated by Django 4.2.13 on 2026-05-08 18:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('github', 'GitHub Repository'), ('zip', 'ZIP Upload')], max_length=20)),
                ('github_url', models.TextField(blank=True, null=True)),
                ('zip_file', models.FileField(blank=True, null=True, upload_to='code_uploads/')),
                ('language_detected', models.CharField(blank=True, max_length=100, null=True)),
                ('build_system_detected', models.CharField(blank=True, max_length=100, null=True)),
                ('build_command', models.TextField(blank=True, null=True)),
                ('sonar_project_key', models.CharField(blank=True, max_length=200, null=True)),
                ('sonar_task_id', models.CharField(blank=True, max_length=200, null=True)),
                ('sonar_summary', models.JSONField(blank=True, null=True)),
                ('sonar_report_url', models.TextField(blank=True, null=True)),
                ('code_summary', models.TextField(blank=True, null=True)),
                ('analysis_status', models.CharField(choices=[('pending', 'Pending'), ('fetching', 'Fetching'), ('scanning', 'Scanning'), ('summarizing', 'Summarizing'), ('questioning', 'Generating Questions'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('analysis_error', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('questions_generated_at', models.DateTimeField(blank=True, null=True)),
                ('project_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_submissions', to='core.projectsubmission')),
            ],
            options={
                'verbose_name': 'Code Submission',
                'verbose_name_plural': 'Code Submissions',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectexaminer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='GeneratedVivaQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('blooms_level', models.CharField(blank=True, choices=[('Remember', 'Remember'), ('Understand', 'Understand'), ('Apply', 'Apply'), ('Analyze', 'Analyze'), ('Evaluate', 'Evaluate'), ('Create', 'Create')], max_length=20, null=True)),
                ('source_type', models.CharField(choices=[('code', 'Code Analysis'), ('sonar', 'Sonar Issues'), ('combined', 'Combined')], max_length=20)),
                ('code_reference', models.TextField(blank=True, null=True)),
                ('sonar_issue_reference', models.JSONField(blank=True, null=True)),
                ('reasoning', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_questions', to='core.codesubmission')),
                ('evaluation_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_code_questions', to='core.evaluationsession')),
            ],
            options={
                'verbose_name': 'Generated Viva Question',
                'verbose_name_plural': 'Generated Viva Questions',
                'ordering': ['-created_at'],
            },
        ),
    ]
