# Generated by Django 4.2.13 on 2026-05-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_codesubmission_alter_groupmember_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesubmission',
            name='quality_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='quality_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('passed', 'Passed'), ('failed', 'Failed')], default='unknown', max_length=20),
        ),
    ]
