# Generated by Django 6.0.4 on 2026-05-11 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_groupmember_id_alter_projectexaminer_id'),
        ('core', '0004_codesubmission_quality_reason_and_more'),
    ]

    operations = [
    ]
