# Generated by Django 6.0.4 on 2026-05-11 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_20260511_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationsession',
            name='demo_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vivaquestion',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examiner_questions', to='core.project'),
        ),
        migrations.AddField(
            model_name='vivaquestion',
            name='question_source',
            field=models.CharField(choices=[('ai', 'AI'), ('examiner', 'Examiner')], default='ai', max_length=20),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectexaminer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vivaquestion',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viva_questions', to='core.evaluationsession'),
        ),
    ]
