# Generated by Django 4.2.13 on 2026-05-11 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_groupmember_id_alter_projectexaminer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivaquestion',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viva_questions', to='core.project'),
        ),
        migrations.AddField(
            model_name='vivaquestion',
            name='question_source',
            field=models.CharField(choices=[('ai', 'AI Generated'), ('examiner', 'Examiner')], default='ai', max_length=20),
        ),
    ]
