# Generated by Django 4.2.13 on 2026-05-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_vivaquestion_project_vivaquestion_question_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubriccriteria',
            name='questions_to_ask',
            field=models.IntegerField(default=3),
        ),
    ]
