# Generated by Django 4.2.13 on 2026-05-13 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_evaluationsession_demo_completed_at_and_more'),
        ('core', '0008_rubriccriteria_questions_to_ask'),
    ]

    operations = [
    ]
