# Generated by Django 4.2.13 on 2026-07-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_week5_bkt_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationsession',
            name='agora_channel_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='evaluationsession',
            name='agora_stt_task_id',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='evaluationsession',
            name='transcript_file_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
