# Generated by Django 4.2.13 on 2026-07-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_restore_agora_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsubmission',
            name='presentation_file_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
