# Generated by Django 4.2.13 on 2026-07-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_projectsubmission_presentation_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationsession',
            name='agora_recording_resource_id',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='evaluationsession',
            name='agora_recording_sid',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
