# Generated by Django 4.2.13 on 2026-07-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_evaluationsession_agora_recording_resource_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationsession',
            name='demo_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
