# Generated by Django 4.2.13 on 2026-07-09 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_evaluationsession_demo_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionPresence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_ping', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='core.evaluationsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session Presence',
                'verbose_name_plural': 'Session Presences',
                'unique_together': {('session', 'user')},
            },
        ),
    ]
