# Generated by Django 4.2.13 on 2026-07-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_sessionpresence'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesubmission',
            name='final_report',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='report_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
