# Generated by Django 4.2.13 on 2026-07-14 12:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_sessionpresence'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoCapturedSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('segment_type', models.CharField(choices=[('audio', 'Audio Transcript'), ('slide', 'Slide Analysis')], max_length=10)),
                ('sequence_number', models.IntegerField(default=1)),
                ('start_time', models.FloatField(default=0.0)),
                ('end_time', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='demo_chunks/')),
                ('processed_text', models.TextField(blank=True, default='')),
                ('is_processed', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, default='')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_segments', to='core.evaluationsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_segments', to='core.studentprofile')),
            ],
            options={
                'verbose_name': 'Demo Captured Segment',
                'verbose_name_plural': 'Demo Captured Segments',
                'ordering': ['sequence_number', 'timestamp'],
            },
        ),
    ]
