# Generated by Django 4.2.13 on 2026-07-16 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_code_final_report'),
        ('core', '0017_democapturedsegment'),
    ]

    operations = [
    ]
