# Generated by Django 4.2.13 on 2026-07-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_merge_20260716_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrecording',
            name='recording_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='face_photo_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
