# Generated by Django 4.2.13 on 2026-07-27 13:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_sessionrecording_recording_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationsession',
            name='max_questions_per_topic',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='evaluationsession',
            name='max_total_questions',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='vivaquestion',
            name='source_criteria_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vivaquestion',
            name='viva_topic_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='RubricGroupingCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_questions', models.IntegerField()),
                ('grouped_criteria', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_grouping_caches', to='core.project')),
            ],
            options={
                'verbose_name': 'Rubric Grouping Cache',
                'verbose_name_plural': 'Rubric Grouping Caches',
                'unique_together': {('project', 'max_questions')},
            },
        ),
        migrations.AddField(
            model_name='evaluationsession',
            name='grouping_cache',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='core.rubricgroupingcache'),
        ),
    ]
