# Generated by Django 4.2.13 on 2026-07-29 05:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_evaluationsession_max_questions_per_topic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationsession',
            name='max_total_questions',
            field=models.IntegerField(default=25),
        ),
        migrations.CreateModel(
            name='ModuleMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_url', models.TextField()),
                ('original_filename', models.CharField(max_length=255)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_materials', to='core.project')),
            ],
            options={
                'verbose_name': 'Module Material',
                'verbose_name_plural': 'Module Materials',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
