# Generated by Django 4.2.13 on 2026-07-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_evaluationsession_max_total_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationsession',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('expired', 'Expired')], default='scheduled', max_length=20),
        ),
    ]
