# Generated by Django 4.2.13 on 2026-08-05 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_evaluationsession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionsummaryreport',
            name='scores_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionsummaryreport',
            name='scores_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='vivaanswer',
            name='examiner_override_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vivaanswer',
            name='examiner_override_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
