# Generated by Django 4.2.13 on 2026-08-07 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_sessionsummaryreport_scores_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalscore',
            name='student',
            field=models.ForeignKey(blank=True, help_text='The specific student this score belongs to in a group session.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_scores_per_student', to='core.studentprofile'),
        ),
        migrations.AddField(
            model_name='sessionsummaryreport',
            name='student',
            field=models.ForeignKey(blank=True, help_text='The specific student this report belongs to in a group session.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summary_reports_per_student', to='core.studentprofile'),
        ),
        migrations.AlterField(
            model_name='sessionsummaryreport',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_reports', to='core.evaluationsession'),
        ),
    ]
