# Generated by Django 4.2.13 on 2026-08-08 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_finalscore_student_sessionsummaryreport_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubriccriteria',
            name='is_individual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vivaanswer',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viva_answers', to='core.studentprofile'),
        ),
        migrations.AddConstraint(
            model_name='sessionsummaryreport',
            constraint=models.UniqueConstraint(fields=('session', 'student'), name='unique_summary_report_per_student'),
        ),
    ]
