# Generated by Django 4.2.13 on 2026-08-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_rubriccriteria_is_individual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationsession',
            name='examiner_paused',
            field=models.BooleanField(default=False),
        ),
    ]
