# Generated by Django 4.2.13 on 2026-08-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_evaluationsession_examiner_paused'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationsession',
            name='viva_weight_percentage',
            field=models.IntegerField(default=100),
        ),
    ]
