# Generated by Django 4.2.13 on 2026-09-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_default_group_rubric_criteria_to_individual'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivaquestion',
            name='closed_at',
            field=models.DateTimeField(blank=True, help_text="Set when the examiner handed the viva back to the AI while this question was still unanswered. The question stays in the report, but is no longer delivered to the student - without this an abandoned interjection is pending forever and freezes that student's screen while the rest of the group moves on.", null=True),
        ),
    ]
