# Generated by Django 4.2.13 on 2026-05-08 12:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_groupmember_id_alter_projectexaminer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VivaQuestionExtension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('source_chunks', models.JSONField(blank=True, null=True)),
                ('criteria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viva_questions', to='core.rubriccriteria')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extension', to='core.vivaquestion')),
            ],
            options={
                'verbose_name': 'Viva Question Extension',
                'verbose_name_plural': 'Viva Question Extensions',
            },
        ),
        migrations.CreateModel(
            name='VivaAnswerExtension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('semantic_similarity_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('llm_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('llm_reasoning', models.TextField(blank=True, null=True)),
                ('next_difficulty_signal', models.CharField(blank=True, choices=[('lower', 'Lower'), ('same', 'Same'), ('higher', 'Higher')], max_length=10, null=True)),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extension', to='core.vivaanswer')),
            ],
            options={
                'verbose_name': 'Viva Answer Extension',
                'verbose_name_plural': 'Viva Answer Extensions',
            },
        ),
        migrations.CreateModel(
            name='SubmissionIndexStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='submissions/reports/')),
                ('faiss_index_path', models.CharField(blank=True, max_length=512, null=True)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('indexing', 'Indexing'), ('indexed', 'Indexed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='index_status', to='core.projectsubmission')),
            ],
            options={
                'verbose_name': 'Submission Index Status',
                'verbose_name_plural': 'Submission Index Statuses',
            },
        ),
    ]
