# Generated by Django 4.2.13 on 2026-05-09 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viva_evaluator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissionindexstatus',
            old_name='indexed_at',
            new_name='processed_at',
        ),
        migrations.RemoveField(
            model_name='submissionindexstatus',
            name='faiss_index_path',
        ),
        migrations.RemoveField(
            model_name='vivaanswerextension',
            name='semantic_similarity_score',
        ),
        migrations.RemoveField(
            model_name='vivaquestionextension',
            name='source_chunks',
        ),
        migrations.AlterField(
            model_name='submissionindexstatus',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
