# Generated by Django 4.2.13 on 2026-05-11 14:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rubriccriteria_questions_to_ask'),
        ('viva_evaluator', '0002_rename_indexed_at_submissionindexstatus_processed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriteriaQuestionHint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hint_text', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_hints', to='core.rubriccriteria')),
            ],
            options={
                'verbose_name': 'Criteria Question Hint',
                'verbose_name_plural': 'Criteria Question Hints',
                'ordering': ['order'],
            },
        ),
    ]
