# Generated by Django 4.2.13 on 2026-07-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viva_evaluator', '0007_rename_viva_eval_a_technol_a59ddc_idx_viva_evalua_technol_5be0eb_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivaanswerextension',
            name='detailed_ai_analysis',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
