# Generated by Django 4.2.13 on 2026-08-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viva_evaluator', '0008_vivaanswerextension_detailed_ai_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivaquestionextension',
            name='fallback_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vivaquestionextension',
            name='generation_audit',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='vivaquestionextension',
            name='validation_degraded',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='vivaquestionextension',
            name='validation_status',
            field=models.CharField(
                choices=[
                    ('not_applicable', 'Not applicable'),
                    ('fully_validated', 'Fully validated'),
                    ('tier1_only_policy', 'Tier 1 only by policy'),
                    ('critic_unavailable', 'Critic unavailable'),
                    ('safe_fallback', 'Safe fallback'),
                    ('rejected', 'Rejected'),
                ],
                db_index=True,
                default='not_applicable',
                max_length=32,
            ),
        ),
    ]
