"""
Critic agent — Tier 2 LLM-based validation of generated questions.

WHEN IT RUNS:
    Only after Tier 1 (programmatic) passes. Tier 1 catches the easy stuff
    (length, anchor regex, single ?, similarity to recent). Tier 2 catches
    the subtler issues that need an LLM judgment:
        - Specificity: does the question reference concrete student work?
        - Bloom alignment: does it actually require the targeted level?
        - Hallucination: does it assert claims not in the retrieved context?

OUTPUT:
    {
        'passed': bool,
        'critique': str,                       # one-sentence reason on fail
        'specificity_score': float (0..1),
        'bloom_alignment_score': float (0..1),
        'hallucination_flag': bool,
    }

INTEGRATION:
    The Questioner runs Tier 1, then if it passes, runs the Critic. On
    failure, the Questioner regenerates with the critique appended to its
    prompt. Maximum 2 Critic retries.
"""

import logging
from dataclasses import dataclass
from typing import List, Dict, Optional

from viva_evaluator.services.llm_service import llm_call

logger = logging.getLogger(__name__)


@dataclass
class CriticInput:
    question_text: str
    target_bloom: str                          # what the Strategist asked for
    target_intent: str                         # the Socratic intent
    retrieved_chunks: List[Dict]               # the only acceptable source of facts
    student_last_answer: Optional[str] = None  # for "you mentioned ..." checks


# =============================================================================
# Public API
# =============================================================================

def critique_question(inp: CriticInput) -> Dict:
    """
    Run Tier 2 LLM-based critique on a question.

    Returns dict with:
        passed:                bool
        critique:              short reason on fail (empty on pass)
        specificity_score:     0..1
        bloom_alignment_score: 0..1
        hallucination_flag:    bool
    """
    prompt = _build_prompt(inp)

    response = llm_call(
        prompt=prompt,
        model='fast',
        expect_json=True,
        max_retries=1,
        fallback={
            'passed': True,
            'critique': '',
            'specificity_score': 0.7,
            'bloom_alignment_score': 0.7,
            'hallucination_flag': False,
        },
    )

    if not isinstance(response, dict):
        # If the fallback or parse path returned something weird, default to pass
        return {
            'passed': True,
            'critique': '',
            'specificity_score': 0.5,
            'bloom_alignment_score': 0.5,
            'hallucination_flag': False,
        }

    # Defensive normalization
    spec = _clamp01(response.get('specificity_score', 0.7))
    bloom = _clamp01(response.get('bloom_alignment_score', 0.7))
    halluc = bool(response.get('hallucination_flag', False))

    # Critic passes if all three quality bars are met
    quality_ok = spec >= 0.5 and bloom >= 0.5 and not halluc
    passed = bool(response.get('passed', quality_ok)) and quality_ok

    return {
        'passed':                passed,
        'critique':              str(response.get('critique', '') or '')[:300],
        'specificity_score':     spec,
        'bloom_alignment_score': bloom,
        'hallucination_flag':    halluc,
    }


# =============================================================================
# Prompt
# =============================================================================

def _build_prompt(inp: CriticInput) -> str:
    from viva_evaluator.services.rag.retrieval import format_chunks_for_prompt

    sources_block = format_chunks_for_prompt(inp.retrieved_chunks, max_chars=1500)

    last_answer_block = ''
    if inp.student_last_answer:
        last_answer_block = (
            f"\nSTUDENT'S LAST ANSWER (verbatim):\n"
            f'"{inp.student_last_answer[:400]}"\n'
        )

    return f"""You are reviewing a viva question generated by another agent.
Your job is to catch quality issues before the question is shown to the student.

QUESTION TO REVIEW:
"{inp.question_text}"

EXAMINER STRATEGY THE QUESTION SHOULD FULFILL:
  Target Bloom level:   {inp.target_bloom}
  Socratic intent:      {inp.target_intent}

RETRIEVED SOURCES (the ONLY valid source of factual claims about the student's
project — anything not present here is hallucinated):

{sources_block}
{last_answer_block}
SCORE THE QUESTION ON THREE DIMENSIONS (each 0.0 to 1.0):

1. SPECIFICITY: does the question reference something concrete from the
   student's actual work, or is it a generic question that could be asked
   of any student on this topic?
       1.0 = anchored to specific code/section/student-quote
       0.5 = generic but on-topic
       0.0 = could be asked of any student in any year

2. BLOOM ALIGNMENT: does the question actually require the cognitive level
   of {inp.target_bloom}? A question that can be answered by recall when
   Evaluate was specified should fail this check.
       1.0 = perfectly matches the target Bloom level
       0.5 = roughly the right level but loose
       0.0 = wrong cognitive level entirely

3. HALLUCINATION FLAG (boolean): does the question assert any claim about
   the student's project that CANNOT be verified from the retrieved sources
   above? Examples of hallucinations:
   - Inventing a function name not in the sources
   - Citing a section/table that doesn't exist
   - Claiming the student wrote something they didn't write

Respond ONLY with valid JSON in this exact shape:
{{
    "passed": true,
    "specificity_score": 0.85,
    "bloom_alignment_score": 0.90,
    "hallucination_flag": false,
    "critique": "<one-sentence reason if passed=false; empty string if passed=true>"
}}

Set passed=false if specificity < 0.5, OR bloom_alignment < 0.5, OR
hallucination_flag is true.
"""


def _clamp01(x) -> float:
    try:
        return max(0.0, min(1.0, float(x)))
    except (TypeError, ValueError):
        return 0.5
