# Generated by Django 4.2.13 on 2026-08-20 15:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0028_project_evaluation_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakerBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('track_ref', models.CharField(blank=True, default='', max_length=64)),
                ('bbox', models.JSONField(blank=True, null=True)),
                ('method', models.CharField(choices=[('arcface', 'ArcFace vs enrollment photo'), ('seating', 'Seating order (left to right)'), ('manual', 'Examiner assigned')], default='arcface', max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('bound_at', models.DateTimeField(auto_now_add=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_bindings', to='core.evaluationsession')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speaker_bindings', to='core.studentprofile')),
            ],
            options={
                'verbose_name': 'Speaker Binding',
                'verbose_name_plural': 'Speaker Bindings',
                'ordering': ['-bound_at'],
            },
        ),
        migrations.CreateModel(
            name='AnswerAttribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share', models.FloatField(default=0.0)),
                ('margin', models.FloatField(default=0.0)),
                ('outcome', models.CharField(default='no_evidence', max_length=20)),
                ('source_breakdown', models.JSONField(blank=True, default=dict)),
                ('co_speakers', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('provisional', 'Provisional (live evidence)'), ('reconciled', 'Reconciled (post-hoc evidence)'), ('confirmed', 'Confirmed by examiner'), ('disputed', 'Post-hoc disagrees after sign-off')], default='provisional', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attribution', to='core.vivaanswer')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_attributions', to='core.examinerprofile')),
                ('provisional_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisional_attributions', to='core.studentprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_attributions', to='core.evaluationsession')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer_attributions', to='core.studentprofile')),
            ],
            options={
                'verbose_name': 'Answer Attribution',
                'verbose_name_plural': 'Answer Attributions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpeakerEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('t_start', models.DateTimeField()),
                ('t_end', models.DateTimeField()),
                ('confidence', models.FloatField(default=1.0)),
                ('source', models.CharField(choices=[('manual', 'Examiner / kiosk selection'), ('agora_stt', 'Agora STT voice tag'), ('agora_volume', 'Agora active speaker'), ('posthoc_cv', 'Post-hoc CV analysis'), ('live_cv', 'Live CV (lip motion x VAD)'), ('submitter', 'Authenticated submitter')], max_length=20)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_evidence', to='core.evaluationsession')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speaker_evidence', to='core.studentprofile')),
            ],
            options={
                'verbose_name': 'Speaker Evidence',
                'verbose_name_plural': 'Speaker Evidence',
                'ordering': ['t_start'],
                'indexes': [models.Index(fields=['session', 't_start', 't_end'], name='attribution_session_91ee1e_idx'), models.Index(fields=['session', 'source'], name='attribution_session_ee0fd1_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='speakerevidence',
            constraint=models.UniqueConstraint(fields=('session', 'source', 'student', 't_start', 't_end'), name='uniq_speaker_evidence_span'),
        ),
        migrations.AddIndex(
            model_name='speakerbinding',
            index=models.Index(fields=['session', 'superseded_at'], name='attribution_session_624314_idx'),
        ),
        migrations.AddIndex(
            model_name='answerattribution',
            index=models.Index(fields=['session', 'status'], name='attribution_session_6e4e67_idx'),
        ),
    ]
