# Generated by Django 4.2.13 on 2026-08-20 20:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_project_evaluation_mode'),
        ('attribution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerContribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share', models.FloatField(default=0.0)),
                ('is_dominant', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Answer Contribution',
                'verbose_name_plural': 'Answer Contributions',
                'ordering': ['-share'],
            },
        ),
        migrations.CreateModel(
            name='UnknownSpeaker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=64)),
                ('track_refs', models.JSONField(blank=True, default=list)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Unknown Speaker',
                'verbose_name_plural': 'Unknown Speakers',
                'ordering': ['label'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='speakerevidence',
            name='uniq_speaker_evidence_span',
        ),
        migrations.AddConstraint(
            model_name='speakerevidence',
            constraint=models.UniqueConstraint(fields=('session', 'source', 'student', 'unknown_speaker', 't_start', 't_end'), name='uniq_speaker_evidence_span'),
        ),
        migrations.AddField(
            model_name='unknownspeaker',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_unknown_speakers', to='core.examinerprofile'),
        ),
        migrations.AddField(
            model_name='unknownspeaker',
            name='resolved_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_from_unknown', to='core.studentprofile'),
        ),
        migrations.AddField(
            model_name='unknownspeaker',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unknown_speakers', to='core.evaluationsession'),
        ),
        migrations.AddField(
            model_name='answercontribution',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='core.vivaanswer'),
        ),
        migrations.AddField(
            model_name='answercontribution',
            name='attribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='attribution.answerattribution'),
        ),
        migrations.AddField(
            model_name='answercontribution',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_contributions', to='core.studentprofile'),
        ),
        migrations.AddField(
            model_name='answercontribution',
            name='unknown_speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_contributions', to='attribution.unknownspeaker'),
        ),
        migrations.AddField(
            model_name='answerattribution',
            name='unknown_speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer_attributions', to='attribution.unknownspeaker'),
        ),
        migrations.AddField(
            model_name='speakerevidence',
            name='unknown_speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='attribution.unknownspeaker'),
        ),
        migrations.AddConstraint(
            model_name='unknownspeaker',
            constraint=models.UniqueConstraint(fields=('session', 'label'), name='uniq_unknown_speaker_label'),
        ),
        migrations.AddIndex(
            model_name='answercontribution',
            index=models.Index(fields=['answer', 'student'], name='attribution_answer__d6e8e2_idx'),
        ),
    ]
