# Generated by Django 4.2.13 on 2026-08-30 08:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0029_vivaanswer_deduplication_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysioDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=64)),
                ('bound_at', models.DateTimeField(auto_now_add=True)),
                ('unbound_at', models.DateTimeField(blank=True, null=True)),
                ('battery_pct', models.IntegerField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physio_devices', to='core.evaluationsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physio_devices', to='core.studentprofile')),
            ],
            options={
                'verbose_name': 'Physio Device',
                'verbose_name_plural': 'Physio Devices',
                'ordering': ['-bound_at'],
            },
        ),
        migrations.CreateModel(
            name='BaselineWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('hr_mean', models.FloatField(blank=True, null=True)),
                ('hr_sd', models.FloatField(blank=True, null=True)),
                ('rmssd', models.FloatField(blank=True, null=True)),
                ('sdnn', models.FloatField(blank=True, null=True)),
                ('beat_count', models.IntegerField(default=0)),
                ('quality', models.FloatField(default=0.0)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physio_baseline_windows', to='core.evaluationsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physio_baseline_windows', to='core.studentprofile')),
            ],
            options={
                'verbose_name': 'Baseline Window',
                'verbose_name_plural': 'Baseline Windows',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PhysioSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('t', models.DateTimeField()),
                ('bpm', models.IntegerField(blank=True, null=True)),
                ('ibi_ms', models.JSONField(blank=True, default=list)),
                ('contact', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='physiology.physiodevice')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physio_samples', to='core.evaluationsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physio_samples', to='core.studentprofile')),
            ],
            options={
                'verbose_name': 'Physio Sample',
                'verbose_name_plural': 'Physio Samples',
                'ordering': ['t'],
                'indexes': [models.Index(fields=['session', 'student', 't'], name='physiology__session_95e993_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='physiosample',
            constraint=models.UniqueConstraint(fields=('session', 'student', 't'), name='uniq_physio_sample_instant'),
        ),
        migrations.AddIndex(
            model_name='physiodevice',
            index=models.Index(fields=['session', 'unbound_at'], name='physiology__session_8d85ed_idx'),
        ),
    ]
