# Generated by Django 4.2.13 on 2026-07-07 05:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0011_evaluationsession_agora_channel_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVSessionReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('artifact', models.JSONField(blank=True, null=True)),
                ('recording_url', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cv_report', to='core.evaluationsession')),
            ],
            options={
                'verbose_name': 'CV Session Report',
                'verbose_name_plural': 'CV Session Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
