# Generated by Django 4.2.13 on 2026-07-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvsessionreport',
            name='modal_call_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
